import SectionTitle from "@/components/SectionTitle";
import Link from "next/link";
import { BrainCircuit, FileSearch, Gauge, ShieldCheck, Workflow, Wrench, ClipboardCheck, Database, Factory, Truck } from "lucide-react";
const items=[
 [Gauge,"Production Intelligence","Watch oil, water, gas, pressures, runtime and well behavior. Surface deviations before they become invisible lost production."],
 [FileSearch,"Measurement Intelligence","Reconcile LACTs, tanks, tickets, gravity, BS&W, meter factors and purchaser settlement."],
 [ClipboardCheck,"Compliance Automation","Track permits, recurring reports, inspections, registrations and renewal windows. Prepare work for human review."],
 [ShieldCheck,"Safety Intelligence","Analyze incidents, near misses, inspections, JSAs, telematics and corrective actions for recurring patterns."],
 [Factory,"Separation Intelligence","Correlate temperature, water cut, treatment, chemical spend and final crude quality to find avoidable cost."],
 [Truck,"Transportation Optimization","Combine tank inventory, production rates, trucks, destinations, wait time and rates to improve dispatch decisions."],
 [Database,"Knowledge Agents","Turn SOPs, manuals, contracts, permits and historical records into a secure internal knowledge system."],
 [Workflow,"Workflow Automation","Replace repetitive copying, report building, document filing, email routing and spreadsheet maintenance."],
 [Wrench,"Custom Software","Build exactly what the operation needs instead of forcing the operation to conform to generic software."],
 [BrainCircuit,"Management Agents","Prepare daily and weekly briefs, identify exceptions and keep managers focused on the decisions that matter."]
] as const;
export const metadata={title:"AI & Automation"};
export default function Page(){return <main><section className="section photo-overlay" style={{backgroundImage:'url(https://upload.wikimedia.org/wikipedia/commons/4/49/Chevron_El_Segundo_Refinery_%284054927810%29.jpg)',backgroundSize:'cover',backgroundPosition:'center'}}><div className="container"><div style={{maxWidth:850}}><div className="kicker">Copperhead Intelligence</div><h1 className="h1">We teach AI the oilfield.</h1><p className="lead">Nearly 25 years of petroleum operations experience, applied to custom software, AI agents, automation and operational analytics.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="btn btn-primary" href="/ai-automation/assessment">AI Opportunity Assessment</Link><Link className="btn btn-secondary" href="/contact">Talk to Copperhead</Link></div></div></div></section><section className="section" style={{background:'#0a0e11'}}><div className="container"><SectionTitle kicker="Practical AI" title="Find the expensive repetition. Find the data nobody is watching. Automate it." copy="Copperhead starts with the operation, not the software. We identify work that can be monitored, analyzed, recommended or safely automated." dark/><div className="grid-3">{items.map(([Icon,t,c])=><div className="card" key={t} style={{padding:22}}><Icon color="#efb346"/><h3>{t}</h3><p className="muted" style={{fontSize:14}}>{c}</p></div>)}</div></div></section><section className="section surface-paper"><div className="container"><SectionTitle kicker="Implementation model" title="Watch. Understand. Recommend. Automate." copy="AI should earn the right to automate. We start by observing the workflow, prove the analysis, then automate only where the boundaries are clear."/><div className="grid-4">{['WATCH','UNDERSTAND','RECOMMEND','AUTOMATE'].map((x,i)=><div key={x} className="card-light" style={{padding:24}}><div className="metric" style={{color:'#b66b25'}}>0{i+1}</div><h3>{x}</h3><p style={{color:'#647078',fontSize:14}}>{['Connect data and identify abnormal conditions or repetitive work.','Add operating context, history and relationships between variables.','Give people a short list of actions or questions worth attention.','Execute proven workflows inside defined permissions and review controls.'][i]}</p></div>)}</div></div></section></main>}
