import Hero from "@/components/Hero";
import MarginStrip from "@/components/MarginStrip";
import TradingViewTicker from "@/components/TradingViewTicker";
import SectionTitle from "@/components/SectionTitle";
import Link from "next/link";
import { capabilityData, intelligenceSeed } from "@/lib/seed";
import { site } from "@/lib/site";
import { BrainCircuit, Calculator, FileSearch, Network, Route, ShieldCheck, Sparkles, Truck, Waves, Wrench } from "lucide-react";

const icons=[Truck,Network,Calculator,Wrench,Waves,BrainCircuit];
export default function Home(){return <main>
  <Hero/><TradingViewTicker/><MarginStrip/>
  <section className="section surface-paper"><div className="container"><SectionTitle kicker="Capabilities" title="The whole barrel matters." copy="Copperhead works across the physical, commercial and digital parts of petroleum operations. We look for the places where value leaks out, then help fix them."/>
    <div className="grid-3">{capabilityData.map((c,i)=>{const Icon=icons[i]||Sparkles;return <Link className="card-light" key={c.slug} href={`/capabilities/${c.slug}`} style={{padding:24}}><Icon size={28} color="#b66b25"/><h3 className="h3" style={{marginTop:16}}>{c.title}</h3><p style={{color:'#59656d',fontSize:14}}>{c.short}</p><span className="eyebrow">Explore capability</span></Link>})}</div>
  </div></section>
  <section className="section photo-overlay" style={{backgroundImage:`url(${site.images.refinery})`,backgroundSize:'cover',backgroundPosition:'center'}}><div className="container"><div style={{maxWidth:720}}><div className="kicker">Copperhead Intelligence</div><h2 className="h1">We do not bring generic AI to the oilfield. <span className="copper">We teach AI the oilfield.</span></h2><p className="lead">Custom software, internal agents, automation and operating analytics built around the way producers actually work.</p><div className="grid-3" style={{marginTop:28}}><div className="card" style={{padding:20}}><BrainCircuit color="#efb346"/><h3>Operational agents</h3><p className="muted">Production surveillance, measurement reconciliation, safety review, compliance and reporting.</p></div><div className="card" style={{padding:20}}><Route color="#efb346"/><h3>Workflow automation</h3><p className="muted">Replace repetitive entry, report building, document routing and deadline tracking.</p></div><div className="card" style={{padding:20}}><ShieldCheck color="#efb346"/><h3>Decision support</h3><p className="muted">Turn thousands of datapoints into a short list of decisions that deserve attention.</p></div></div><Link className="btn btn-primary" href="/ai-automation" style={{marginTop:24}}>Explore AI & Automation</Link></div></div></section>
  <section className="section" style={{background:'#0b1013'}}><div className="container"><SectionTitle kicker="Producer Desk" title="Built for the people who produce." copy="Free tools, practical information and trusted resources. No enterprise price tag." dark/>
    <div className="grid-4"><Link className="card" href="/measurement" style={{padding:22}}><Calculator color="#efb346"/><h3>Measurement Workbench</h3><p className="muted">LACT, weighed loads, ticket checks and temperature sensitivity.</p></Link><Link className="card" href="/contract-intelligence" style={{padding:22}}><FileSearch color="#efb346"/><h3>Contract Intelligence</h3><p className="muted">Understand measurement, pricing, obligations and commercial attention items.</p></Link><Link className="card" href="/intelligence" style={{padding:22}}><Sparkles color="#efb346"/><h3>Industry Intelligence</h3><p className="muted">Markets, state news, rules, legislation, technology and funding.</p></Link><Link className="card" href="/library" style={{padding:22}}><Waves color="#efb346"/><h3>Field Library</h3><p className="muted">Measurement, contracts, operations, logistics, regulation and technology explained.</p></Link></div>
  </div></section>
  <section className="section surface-paper"><div className="container"><SectionTitle kicker="Copperhead Intelligence" title="What operators should know now." copy="A curated desk for market context, regulatory change, new technology and opportunities that may matter to producers."/><div className="grid-4">{intelligenceSeed.map(x=><a className="card-light" style={{padding:22}} href={x.href} key={x.title}><span className="badge">{x.category}</span><h3 style={{marginTop:16}}>{x.title}</h3><p style={{color:'#66727a',fontSize:14}}>{x.summary}</p></a>)}</div><div style={{marginTop:24}}><Link className="btn btn-primary" href="/intelligence">Open Copperhead Intelligence</Link></div></div></section>
  <section className="section photo-overlay" style={{backgroundImage:`url(${site.images.lostHills})`,backgroundSize:'cover',backgroundPosition:'center'}}><div className="container"><div style={{maxWidth:770}}><div className="kicker">Independent producers</div><h2 className="h1">Independent producers are the soul of oil.</h2><p className="lead">They are families, employers, neighbors and members of the communities where they operate. Copperhead believes they should have access to serious knowledge, useful technology and experienced people without carrying an enterprise-sized staff.</p><Link className="btn btn-primary" href="/independent-producers">Why we care</Link></div></div></section>
</main>}
