"use client";
import { useMemo, useState } from "react";
import { Bot, ClipboardCheck, Database, FileText, Gauge, Workflow } from "lucide-react";
const areas=[
 {key:'entry',icon:Workflow,title:'Repetitive entry',copy:'Copying between spreadsheets, portals, email and accounting systems.'},
 {key:'reports',icon:FileText,title:'Manual reporting',copy:'Recurring production, management, customer or compliance reports.'},
 {key:'data',icon:Gauge,title:'Operational data',copy:'Well, facility or measurement data that nobody can review continuously.'},
 {key:'docs',icon:Database,title:'Document knowledge',copy:'Contracts, SOPs, permits and manuals that are hard to search or compare.'},
 {key:'compliance',icon:ClipboardCheck,title:'Compliance tracking',copy:'Renewals, reports, training, inspections and recurring deadlines.'},
 {key:'agents',icon:Bot,title:'Internal assistance',copy:'Staff repeatedly answering the same questions or building the same work product.'}
];
export default function AutomationAssessment(){const [selected,setSelected]=useState<string[]>(['entry','reports']);const [hours,setHours]=useState(15);const [labor,setLabor]=useState(42);const recovery=useMemo(()=>hours*52*labor*.8,[hours,labor]);function toggle(k:string){setSelected(s=>s.includes(k)?s.filter(x=>x!==k):[...s,k])}return <div className="card-light" style={{padding:22}}><div className="grid-3">{areas.map(a=>{const Icon=a.icon;const on=selected.includes(a.key);return <button type="button" onClick={()=>toggle(a.key)} key={a.key} style={{textAlign:'left',border:on?'1px solid #c98431':'1px solid #dce1e4',background:on?'#fff6e9':'white',borderRadius:10,padding:16,cursor:'pointer'}}><Icon color="#b66b25"/><h3>{a.title}</h3><p style={{color:'#67737b',fontSize:13}}>{a.copy}</p></button>})}</div><div className="grid-2" style={{marginTop:24}}><div className="form-field"><label>Hours per week spent on one repetitive workflow</label><input type="number" value={hours} onChange={e=>setHours(Number(e.target.value))}/></div><div className="form-field"><label>Loaded labor cost per hour</label><input type="number" value={labor} onChange={e=>setLabor(Number(e.target.value))}/></div></div><div className="callout" style={{color:'#674318',marginTop:20}}><b>Illustrative recoverable capacity: ${recovery.toLocaleString(undefined,{maximumFractionDigits:0})}/year</b><div style={{fontSize:12}}>Uses an 80% automation assumption for one workflow. Actual savings depend on process quality, exceptions, software access and human review requirements.</div></div><div style={{marginTop:18}}><a className="btn btn-primary" href="/contact">Build my Copperhead AI roadmap</a></div></div>}
