"use client";
import { useMemo, useState } from "react";
import { calculateLact, calculateTruckScale, correctObservedApiTo60, estimateTemperatureRange } from "@/lib/measurement";
import { AlertTriangle, CheckCircle2, Save, Scale, SlidersHorizontal, Truck } from "lucide-react";

type Mode="lact"|"truck"|"checker";
function n(v:string){const x=Number(v);return Number.isFinite(x)?x:0}
function fmt(v:number|null|undefined,d=3){return v==null||!Number.isFinite(v)?"Not calculated":v.toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d})}

export default function MeasurementWorkbench(){
 const [mode,setMode]=useState<Mode>('lact');
 const [gravityType,setGravityType]=useState<'observed'|'corrected'>('observed');
 const [observedApi,setObservedApi]=useState('38.2');
 const [sampleTemp,setSampleTemp]=useState('97');
 const [correctedApi,setCorrectedApi]=useState('16.4');
 const [start,setStart]=useState('340'); const [stop,setStop]=useState('510'); const [mf,setMf]=useState('1.0000'); const [bsw,setBsw]=useState('0.02');
 const [tempMode,setTempMode]=useState<'known'|'estimate'|'unknown'>('estimate');
 const [flowTemp,setFlowTemp]=useState('97'); const [heated,setHeated]=useState<'yes'|'no'|'unknown'>('unknown'); const [cpl,setCpl]=useState('');
 const [heavy,setHeavy]=useState('80000'); const [light,setLight]=useState('27500');
 const [reportedGsv,setReportedGsv]=useState(''); const [reportedNsv,setReportedNsv]=useState('');
 const api60=useMemo(()=>gravityType==='corrected'?n(correctedApi):correctObservedApiTo60(n(observedApi),n(sampleTemp)),[gravityType,correctedApi,observedApi,sampleTemp]);
 const range=estimateTemperatureRange(api60,heated==='yes'?true:heated==='no'?false:undefined);
 const effectiveTemp=tempMode==='known'?n(flowTemp):tempMode==='estimate'?(range[0]+range[1])/2:null;
 const lact=calculateLact({meterStart:n(start),meterStop:n(stop),meterFactor:n(mf)||1,api60,bswPercent:bsw===''?null:n(bsw),flowingTempF:effectiveTemp,cpl:cpl===''?null:n(cpl)});
 const low=calculateLact({meterStart:n(start),meterStop:n(stop),meterFactor:n(mf)||1,api60,bswPercent:bsw===''?null:n(bsw),flowingTempF:range[0],cpl:cpl===''?null:n(cpl)});
 const high=calculateLact({meterStart:n(start),meterStop:n(stop),meterFactor:n(mf)||1,api60,bswPercent:bsw===''?null:n(bsw),flowingTempF:range[1],cpl:cpl===''?null:n(cpl)});
 const truck=calculateTruckScale({heavyLb:n(heavy),lightLb:n(light),api60,bswPercent:bsw===''?null:n(bsw)});
 const status=tempMode==='known'?'Verified':tempMode==='estimate'?'Estimated Range':'Partial';
 function save(){const payload={savedAt:new Date().toISOString(),mode,api60,lact,truck};localStorage.setItem('copperhead-last-calculation',JSON.stringify(payload));alert('Calculation saved in this browser. Connect Supabase later for account-level persistence.');}
 const inputBlock=<>
   <div className="form-field"><label>Gravity input</label><select value={gravityType} onChange={e=>setGravityType(e.target.value as any)}><option value="observed">Observed API + sample temperature</option><option value="corrected">Corrected API @ 60°F</option></select></div>
   {gravityType==='observed'?<div className="grid-2"><div className="form-field"><label>Observed API</label><input inputMode="decimal" value={observedApi} onChange={e=>setObservedApi(e.target.value)}/></div><div className="form-field"><label>Sample temperature °F</label><input inputMode="decimal" value={sampleTemp} onChange={e=>setSampleTemp(e.target.value)}/></div></div>:<div className="form-field"><label>Corrected API @ 60°F</label><input inputMode="decimal" value={correctedApi} onChange={e=>setCorrectedApi(e.target.value)}/></div>}
   <div className="result-mini"><span>API @ 60°F</span><b>{fmt(api60,2)}°</b><small>{gravityType==='observed'?'Calculated':'Entered'}</small></div>
   <div className="form-field"><label>BS&W %</label><input inputMode="decimal" value={bsw} onChange={e=>setBsw(e.target.value)} placeholder="Leave blank if unknown"/></div>
 </>;
 return <div className="workbench"><style jsx>{`
 .workbench{background:#f7f8f8;color:#172026;border-radius:16px;overflow:hidden;border:1px solid #374148;box-shadow:0 22px 55px rgba(0,0,0,.3)}.tabs{display:flex;gap:2px;background:#0e1418;padding:10px}.tabs button{border:0;background:transparent;color:#cfd6da;padding:11px 14px;border-radius:6px;font-weight:800;cursor:pointer}.tabs button.active{background:linear-gradient(180deg,#d69945,#9d5b22);color:#14100b}.body{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(0,.95fr);min-height:590px}.inputs{padding:24px;border-right:1px solid #dfe4e6;display:grid;align-content:start;gap:15px}.results{padding:24px;display:grid;align-content:start;gap:15px}.result-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.result{background:white;border:1px solid #dfe4e6;border-radius:9px;padding:13px}.result span,.result-mini span{display:block;font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#66727a;font-weight:800}.result b{font-size:1.35rem}.result-mini{display:grid;grid-template-columns:1fr auto;align-items:center;background:#eef1f2;border-radius:8px;padding:11px 12px}.result-mini b{color:#a75f22}.result-mini small{grid-column:1/-1;color:#7b858c}.status{display:flex;gap:10px;align-items:flex-start;padding:13px;border-radius:9px;background:#fff4e5;border:1px solid #e8c893;color:#68451d}.sensitivity{background:#11181c;color:white;border-radius:12px;padding:17px}.bar{height:8px;border-radius:999px;background:linear-gradient(90deg,#cd8433,#f0bb59);margin:13px 0;position:relative}.bar:after{content:"";position:absolute;left:50%;top:50%;width:16px;height:16px;background:#fff;border-radius:50%;transform:translate(-50%,-50%);box-shadow:0 0 0 4px rgba(255,255,255,.15)}.split{display:flex;justify-content:space-between;font-size:12px;color:#c9d0d4}.actions{display:flex;gap:10px;flex-wrap:wrap}.actions button{flex:1}.small-note{font-size:12px;color:#707b83}.compare{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.compare .result strong{display:block;font-size:1.4rem}.diff{grid-column:1/-1;background:#fff8ec;border:1px solid #e8cf9e;padding:12px;border-radius:9px}.section-label{font-size:12px;font-weight:900;text-transform:uppercase;letter-spacing:.09em;color:#647078;border-bottom:1px solid #e1e5e7;padding-bottom:7px}.form-field label{color:#273239}.form-field input,.form-field select{background:white}
 @media(max-width:850px){.body{grid-template-columns:1fr}.inputs{border-right:0;border-bottom:1px solid #dfe4e6}.result-grid{grid-template-columns:1fr 1fr}}@media(max-width:540px){.tabs{overflow:auto}.tabs button{white-space:nowrap}.result-grid,.compare{grid-template-columns:1fr}.body{min-height:0}.inputs,.results{padding:16px}}
 `}</style>
 <div className="tabs"><button className={mode==='lact'?'active':''} onClick={()=>setMode('lact')}><SlidersHorizontal size={15} style={{verticalAlign:'middle',marginRight:6}}/>LACT / Metered</button><button className={mode==='truck'?'active':''} onClick={()=>setMode('truck')}><Truck size={15} style={{verticalAlign:'middle',marginRight:6}}/>Truck Scale</button><button className={mode==='checker'?'active':''} onClick={()=>setMode('checker')}><CheckCircle2 size={15} style={{verticalAlign:'middle',marginRight:6}}/>Ticket Checker</button></div>
 <div className="body"><div className="inputs"><div className="section-label">Input data</div>{inputBlock}
 {mode!=='truck'&&<><div className="grid-2"><div className="form-field"><label>Meter start</label><input value={start} onChange={e=>setStart(e.target.value)}/></div><div className="form-field"><label>Meter stop</label><input value={stop} onChange={e=>setStop(e.target.value)}/></div></div><div className="form-field"><label>Meter factor</label><input value={mf} onChange={e=>setMf(e.target.value)}/></div><div className="form-field"><label>Flowing temperature</label><select value={tempMode} onChange={e=>setTempMode(e.target.value as any)}><option value="known">Known average / ticket temperature</option><option value="estimate">Estimate a field range</option><option value="unknown">Unknown, stop before GSV</option></select></div>{tempMode==='known'&&<div className="form-field"><label>Average flowing temperature °F</label><input value={flowTemp} onChange={e=>setFlowTemp(e.target.value)}/></div>}{tempMode==='estimate'&&<div className="form-field"><label>Is the crude intentionally heated?</label><select value={heated} onChange={e=>setHeated(e.target.value as any)}><option value="unknown">Unknown</option><option value="yes">Yes</option><option value="no">No</option></select></div>}<div className="form-field"><label>CPL, if known</label><input value={cpl} onChange={e=>setCpl(e.target.value)} placeholder="Leave blank if pressure correction is unavailable"/></div></>}
 {mode==='truck'&&<><div className="grid-2"><div className="form-field"><label>Loaded / heavy weight lb</label><input value={heavy} onChange={e=>setHeavy(e.target.value)}/></div><div className="form-field"><label>Light / tare weight lb</label><input value={light} onChange={e=>setLight(e.target.value)}/></div></div></>}
 {mode==='checker'&&<div className="grid-2"><div className="form-field"><label>Reported GSV</label><input value={reportedGsv} onChange={e=>setReportedGsv(e.target.value)}/></div><div className="form-field"><label>Reported NSV</label><input value={reportedNsv} onChange={e=>setReportedNsv(e.target.value)}/></div></div>}
 </div><div className="results"><div className="section-label">Calculation results</div>
 {mode==='truck'?<><div className="result-grid"><div className="result"><span>Net cargo weight</span><b>{fmt(truck.netWeightLb,0)} lb</b></div><div className="result"><span>Density in air @ 60°F</span><b>{fmt(truck.lbPerGal,4)} lb/gal</b></div><div className="result"><span>Gross standard volume</span><b>{fmt(truck.gsv,2)} BBL</b></div><div className="result"><span>Net standard volume</span><b className="copper">{fmt(truck.nsv,2)} BBL</b></div></div><div className="status"><Scale size={20}/><div><b>Weight-derived standard volume</b><div className="small-note">Uses corrected API gravity @ 60°F and scale weight. BS&W is applied when supplied.</div></div></div></>:<><div className="result-grid"><div className="result"><span>Indicated volume</span><b>{fmt(lact.indicated,2)} BBL</b></div><div className="result"><span>Meter corrected</span><b>{fmt(lact.meterCorrected,2)} BBL</b></div><div className="result"><span>Gross standard volume</span><b>{fmt(lact.gsv,2)} BBL</b></div><div className="result"><span>Net standard volume</span><b className="copper">{fmt(lact.nsv,2)} BBL</b></div></div><div className="status">{status==='Verified'?<CheckCircle2 size={20}/>:<AlertTriangle size={20}/>}<div><b>{status}</b><div className="small-note">{tempMode==='known'?'A supplied flowing temperature was used.':'Temperature is estimated or missing. Pressure correction is applied only if a CPL is supplied.'}</div></div></div>{tempMode==='estimate'&&<div className="sensitivity"><b>Temperature sensitivity</b><div className="bar"/><div className="split"><span>{range[0]}°F<br/>{fmt(low.nsv,2)} BBL NSV</span><span style={{textAlign:'center'}}>Working midpoint<br/><b>{effectiveTemp}°F</b></span><span style={{textAlign:'right'}}>{range[1]}°F<br/>{fmt(high.nsv,2)} BBL NSV</span></div></div>}{mode==='checker'&&<div className="compare"><div className="result"><span>Reported GSV</span><strong>{reportedGsv||'--'}</strong></div><div className="result"><span>Copperhead GSV</span><strong>{fmt(lact.gsv,2)}</strong></div><div className="result"><span>Reported NSV</span><strong>{reportedNsv||'--'}</strong></div><div className="result"><span>Copperhead NSV</span><strong>{fmt(lact.nsv,2)}</strong></div><div className="diff"><b>Variance</b><div>{reportedNsv&&lact.nsv!=null?`${fmt(lact.nsv-n(reportedNsv),2)} BBL from reported NSV`:'Enter the reported NSV to compare.'}</div></div></div>}</>}
 <div className="actions"><button className="btn btn-primary" onClick={save}><Save size={16}/>Save calculation</button></div><div className="small-note">Copperhead does not invent missing field data. Estimated temperature ranges are operational estimates, not measured custody transfer temperatures.</div>
 </div></div></div>
}
