import { NextResponse } from "next/server";

type Item={title:string;url:string;source:string;published?:string;summary?:string;category?:string};
const fallback:Item[]=[
 {title:'CalGEM Notices to Operators',url:'https://www.conservation.ca.gov/calgem/for_operators/Pages/NoticetoOperator.aspx',source:'CalGEM',summary:'Official California operator notices and guidance.',category:'Regulation'},
 {title:'Texas Railroad Commission',url:'https://www.rrc.texas.gov/',source:'Texas RRC',summary:'Official Texas oil and gas news, announcements and data.',category:'State'},
 {title:'Federal Register',url:'https://www.federalregister.gov/',source:'Federal Register',summary:'Rules, proposed rules, notices and agency actions.',category:'Federal'},
 {title:'DOE oil and gas technology programs',url:'https://www.energy.gov/hgeo',source:'U.S. Department of Energy',summary:'Research, technology and funding activity relevant to oil and gas.',category:'Technology'}
];
function niceDate(x:any){if(!x)return undefined;try{return new Date(x).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}catch{return String(x)}}
async function gdelt(query:string,category:string){const u=new URL('https://api.gdeltproject.org/api/v2/doc/doc');u.searchParams.set('query',query);u.searchParams.set('mode','ArtList');u.searchParams.set('maxrecords','12');u.searchParams.set('format','json');u.searchParams.set('sort','HybridRel');const r=await fetch(u,{next:{revalidate:900}});if(!r.ok)return[];const j=await r.json();return (j.articles||[]).map((a:any)=>({title:a.title,url:a.url,source:a.domain||a.sourcecountry||'News source',published:niceDate(a.seendate),summary:a.socialimage?'Current industry coverage selected by Copperhead Intelligence.':'Current industry coverage selected by Copperhead Intelligence.',category})) as Item[]}
async function crossref(query:string){const u=new URL('https://api.crossref.org/works');u.searchParams.set('query.title',query);u.searchParams.set('filter','from-pub-date:2025-01-01');u.searchParams.set('rows','10');u.searchParams.set('sort','published');u.searchParams.set('order','desc');const r=await fetch(u,{next:{revalidate:7200}});if(!r.ok)return[];const j=await r.json();return (j.message?.items||[]).map((a:any)=>({title:Array.isArray(a.title)?a.title[0]:a.title||'Research item',url:a.URL,source:a.publisher||'Research publisher',published:a.published?.['date-parts']?.[0]?.join('-'),summary:'Recent research metadata surfaced for technical review. Copperhead recommends reading the source before applying any field conclusion.',category:'Technology'})) as Item[]}
async function federalRegister(){const u=new URL('https://www.federalregister.gov/api/v1/documents.json');u.searchParams.set('per_page','8');u.searchParams.set('order','newest');u.searchParams.set('conditions[term]','oil gas petroleum pipeline methane');const r=await fetch(u,{next:{revalidate:1800}});if(!r.ok)return[];const j=await r.json();return (j.results||[]).map((a:any)=>({title:a.title,url:a.html_url,source:(a.agencies||[]).map((x:any)=>x.name).join(', ')||'Federal Register',published:niceDate(a.publication_date),summary:a.abstract||'Federal rulemaking or notice potentially relevant to petroleum operations.',category:a.type||'Federal'})) as Item[]}
export async function GET(req:Request){const url=new URL(req.url);const state=url.searchParams.get('state')||'all';const kind=url.searchParams.get('kind')||'news';try{let items:Item[]=[];if(kind==='technology')items=await crossref('oil gas separation corrosion hydrogen sulfide produced water artificial lift automation');else if(kind==='funding')items=await gdelt('("oil and gas" OR petroleum) (grant OR funding OR "funding opportunity")','Funding');else{const q=state==='all'?'("oil and gas" OR petroleum OR "crude oil")':`("oil and gas" OR petroleum OR "crude oil") "${state}"`;const [news,fed]=await Promise.all([gdelt(q,state==='all'?'Industry':state),federalRegister()]);items=[...news,...fed].slice(0,16)}return NextResponse.json({items:items.length?items:fallback})}catch(e){console.error(e);return NextResponse.json({items:fallback})}}
