import { capabilityData } from "@/lib/seed";
import { notFound } from "next/navigation";
import Link from "next/link";
const detail:Record<string,string[]>={
 "transportation-logistics":["Crude oil transportation","Diesel and petroleum distillates","Transmix and specialty petroleum movements","Field to pipeline and refinery logistics","Refinery to buyer movements","Truck routing and destination analysis"],
 "marketing-market-access":["Producer market placement","Buyer and refinery relationships","Marketing group coordination","Alternative destination analysis","Transportation-aware pricing comparisons","Commercial routing and market access"],
 "measurement-custody-transfer":["LACT and dynamic measurement review","Tank gauging and field sampling","API gravity and BS&W","Run ticket verification","Volume reconciliation","Measurement and settlement clause analysis"],
 "operations-consulting":["Production and facility review","Workflow and cost analysis","Field operating practices","Process bottleneck identification","Treatment economics","Management systems and reporting"],
 "separation-optimization":["Heat and chemical cost review","Emulsion and treatment analysis","Separator and heater performance","Residence time and throughput analysis","Emerging separation technologies","Saleable barrel economics"],
 "custom-software-ai":["Custom dashboards and software","Internal AI agents","Production and measurement analytics","Compliance and paperwork automation","Document intelligence","Repetitive computer workflow automation"]
};
export async function generateStaticParams(){return capabilityData.map(x=>({slug:x.slug}))}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=capabilityData.find(x=>x.slug===slug);if(!c)notFound();return <main className="surface-paper"><section className="section"><div className="container"><div className="kicker">Copperhead capability</div><h1 className="h1" style={{color:'#13191d'}}>{c.title}</h1><p style={{fontSize:'1.2rem',color:'#536069',maxWidth:820}}>{c.short}</p><div className="grid-2" style={{marginTop:40}}><div className="card-light" style={{padding:28}}><h2>What we bring</h2><div style={{display:'grid',gap:12}}>{detail[slug].map(x=><div key={x} style={{padding:'11px 0',borderBottom:'1px solid #e4e7e9',fontWeight:750}}>{x}</div>)}</div></div><div style={{background:'#0b1013',color:'white',padding:30,borderRadius:18}}><div className="kicker">Why it matters</div><h2 style={{fontFamily:'Georgia,serif',fontSize:36}}>The barrel does not care which department owns the problem.</h2><p className="muted">Measurement can change settlement. Routing can erase a price advantage. Treatment can consume margin before the barrel leaves the lease. Copperhead looks across the handoffs.</p><Link className="btn btn-primary" href="/contact">Discuss a problem</Link></div></div></div></section></main>}
